baseURL: 'https://learninglion.nl/'
disablePathToLower: true
preserveTaxonomyNames: true
titleCaseStyle: 'none'

markup:
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  author = "authors"
  tags = "tags"
    

