baseURL = 'https://learninglion.nl/'
languageCode = 'en-us'
title = 'Learning Lion'
theme = 'hugo-book'
disablePathToLower = false
titleCaseStyle = 'none'
preserveTaxonomyNames = true

BookLogo = 'LL-logo.png'

[taxonomies]
  author = "authors"
  tags = "tags"

[markup]
  [markup.goldmark]  
    [markup.goldmark.renderer]
      unsafe = true
