baseURL = 'https://learninglion.nl/'
languageCode = 'en-us'
title = 'Learning Lion'
theme = 'hugo-book'
disablePathToLower = true
titleCaseStyle = 'none'

BookLogo = 'LL-logo.png'

[taxonomies]
  author = "authors"

[markup]
  [markup.goldmark]  
    [markup.goldmark.renderer]
      unsafe = true
