baseURL = 'https://learninglion.nl/'
languageCode = 'en-us'
title = 'Learning Lion'
theme = 'hugo-book'

# (Optional) Set this to true if you use capital letters in file names
disablePathToLower = true
preserveTaxonomyNames = true

BookLogo = 'LL-logo.png'

[markup]
  [markup.goldmark]  
    [markup.goldmark.renderer]
      unsafe = true
